# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled (1).ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtWebEngineWidgets import QWebEngineView

from launchcore import *

modpack = check()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        makefolder("./instance")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 658)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(972, 658))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("W:/Workspace/MRS Launcher/mrs.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 10pt \"나눔고딕\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_3.setGeometry(QtCore.QRect(0, 0, 941, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_3.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_3.setSizePolicy(sizePolicy)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.list_modpack = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_modpack.sizePolicy().hasHeightForWidth())
        self.list_modpack.setSizePolicy(sizePolicy)
        self.list_modpack.setObjectName("list_modpack")
        self.list_modpack.addItems(modpack)
        self.list_modpack.setCurrentRow(0)
        self.list_modpack.setStyleSheet("font: 15pt \"MS Gothic\";")
        self.verticalLayout_2.addWidget(self.list_modpack)
        self.button_refresh = QtWidgets.QPushButton(self.widget)
        self.button_refresh.setObjectName("button_refresh")
        self.verticalLayout_2.addWidget(self.button_refresh)
        self.horizontalWidget = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinbox_ram = QtWidgets.QSpinBox(self.horizontalWidget)
        self.spinbox_ram.setMinimum(4096)
        self.spinbox_ram.setMaximum(999999999)
        self.spinbox_ram.setObjectName("spinbox_ram")
        self.horizontalLayout_2.addWidget(self.spinbox_ram)
        self.verticalLayout_2.addWidget(self.horizontalWidget)
        self.horizontalLayout_3.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget(self.horizontalWidget_3)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.web = QWebEngineView(self.widget1)
        self.web.setUrl(QUrl("https://gametowndev.tk/news.html"))
        self.web.setObjectName("web")
        self.verticalLayout.addWidget(self.web)
        self.horizontalWidget1 = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget1.setSizePolicy(sizePolicy)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridWidget = QtWidgets.QWidget(self.horizontalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setMinimumSize(QtCore.QSize(0, 71))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.text_pass = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_pass.sizePolicy().hasHeightForWidth())
        self.text_pass.setSizePolicy(sizePolicy)
        self.text_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_pass.setClearButtonEnabled(False)
        self.text_pass.setObjectName("text_pass")
        self.gridLayout.addWidget(self.text_pass, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 27))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.text_id = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_id.sizePolicy().hasHeightForWidth())
        self.text_id.setSizePolicy(sizePolicy)
        self.text_id.setObjectName("text_id")
        self.gridLayout.addWidget(self.text_id, 0, 1, 1, 1)
        self.button_launch = QtWidgets.QPushButton(self.gridWidget)
        self.button_launch.setObjectName("button_launch")
        self.gridLayout.addWidget(self.button_launch, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.gridWidget)
        self.verticalLayout.addWidget(self.horizontalWidget1)
        self.horizontalLayout_3.addWidget(self.widget1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 560, 931, 89))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.text_jvm = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.text_jvm.setObjectName("text_jvm")
        self.horizontalLayout_4.addWidget(self.text_jvm)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.button_refresh.clicked.connect(lambda : self.refresh_modpack(self))
        self.button_launch.clicked.connect(lambda : launchwrapper(self,self.text_id,self.text_pass,self.list_modpack))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def refresh_modpack(self, list_modpack):
        modpack = check()
        self.list_modpack.clear()
        self.list_modpack.addItems(modpack)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRS Launcher"))
        self.label.setText(_translate("MainWindow", "모드팩 목록"))
        self.button_refresh.setText(_translate("MainWindow", "새로고침"))
        self.label_3.setText(_translate("MainWindow", "램 할당량"))
        self.spinbox_ram.setSuffix(_translate("MainWindow", "MB"))
        self.label_2.setText(_translate("MainWindow", "ID/이메일"))
        self.label_4.setText(_translate("MainWindow", "비밀번호"))
        self.button_launch.setText(_translate("MainWindow", "실행"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>JVM Arguments</p><p>(램 할당량은 이곳에 쓰지 말아주세요)</p><p>(아무거나 쓰지마세요)</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
